# Generated by Django 5.2.5 on 2025-08-27 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0003_order_orderitem'),
        ('VENDOR', '0006_alter_vendorregister_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VENDOR.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USER.register')),
            ],
        ),
    ]
